[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.68.3"
PYTHON_VERSION = "3.9"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
