[build]
publish = "public"
command = "chmod +x setup_env_pip.sh && ./setup_env_pip.sh && make production-build"

[build.environment]
HUGO_VERSION = "0.68.3"
PYTHON_VERSION = "3.9"
NODE_VERSION = "18"

[context.deploy-preview]
command = "chmod +x setup_env_pip.sh && ./setup_env_pip.sh && make preview-build"

[context.branch-deploy]
command = "chmod +x setup_env_pip.sh && ./setup_env_pip.sh && make preview-build"
